# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('suggested_by', models.CharField(default='Null', max_length=120)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('has_shown', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
